# runs:
#   using: 'node16'
#   main: 'main.js'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install

      - name: Builds using the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/build -v ${{ github.workspace }}/_site:/build/_site \
          ghcr.io/tadman/jekyll-builder:latest /bin/bash -c "chmod -R 777 /build && jekyll build --future"

      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          ssh-key: ${{ secrets.DEPLOY_KEY }}
