# runs:
#   using: 'node16'
#   main: 'main.js'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install

      - uses: docker/login-action@v1
      - name: Builds using the jekyll/builder container
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
        run: rake build

      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          ssh-key: ${{ secrets.DEPLOY_KEY }}
